apiVersion: v1
kind: Service
metadata:
  name: progressive-delivery
  namespace: progressive
  labels:
    app: progressive-delivery
spec:
  selector:
    app: progressive-delivery
  ports:
    - name: http
      port: 80
      targetPort: 8000
